### PR TITLE
Issue #105 is closed

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by nene** [comment]
Ahemm... but issue #105 is not closed.

**Comment by graingert** [comment]
@nene sorry I mean https://github.com/mohebifar/lebab/issues/110 is closed, which fixes #105

**Comment by graingert** [comment]
Eg:
> Detect .bind(this) when converting to arrow function #105

**Comment by nene** [comment]
Issue #105 is indeed referenced in release notes of 1.1.0, but it's not fully fixed. Only the most problematic case is fixed, but Recast issue https://github.com/benjamn/recast/issues/264 is not fixed, and therefore this one isn't as well.

**Comment by graingert** [comment]
@nene ah I misunderstood

**Pull request closed without merging**
