### PR TITLE
Prevent variable name clashes with Object.prototype methods

### PR DESCRIPTION
**Pull request by RReverser**

### CODE REVIEW

**Comment by nene** [comment]
Looks like a solid improvement. Didn't even know one can use `Object.create()` like so.

Would it be a lot to ask you to provide a test that's fixed by this change?

**Comment by RReverser** [comment]
I was just quickly looking into what caused my error of `constructor` clash as installed lebab to decompile one script, but yeah, can do that later.

**Comment by nene** [comment]
Added a test by myself. Merged.

**Comment by RReverser** [comment]
Oach. Been busy and totally forgot about it, sorry for that.

**Pull request merged**
